myodoo_recrut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('salary_calc.urls'))
]

salary_calc/urls.py
from django.urls import path
from . import views

app_name = 'salary_calc'

urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.results, name='results'),
    path('get_salary', views.get_salary, name='get_salary'),
]

salary_calc/models.py
from django.db import models
from django.utils import timezone

salary_calc/forms.py
from django import forms

class SalaryForm(forms.Form):
    param1 = forms.IntegerField(label='1 - Wynagrodzenie brutto', min_value=1500)
    param2 = forms.IntegerField(label='2 - Wynagrodzenie brutto', min_value=1500)
    param3 = forms.IntegerField(label='3 - Wynagrodzenie brutto', min_value=1500)
    param4 = forms.IntegerField(label='4 - Wynagrodzenie brutto', min_value=1500)
    param5 = forms.IntegerField(label='5 - Wynagrodzenie brutto', min_value=1500)
    param6 = forms.IntegerField(label='6 - Wynagrodzenie brutto', min_value=1500)

salary_calc/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .forms import SalaryForm

from  . modules.salary import check_salary
from . modules.graph import Graph

def index(request):
    return render(request, 'salary_calc/index.html')

def results(request):
    return render(request, 'salary_calc/results.html')

def get_salary(request):
    if request.method == 'POST':
        form = SalaryForm(request.POST or None)
        if form.is_valid():
            print(request.POST)

            param1_brutto = request.POST.get('param1')
            param2_brutto = request.POST.get('param2')
            param3_brutto = request.POST.get('param3')
            param4_brutto = request.POST.get('param4')
            param5_brutto = request.POST.get('param5')
            param6_brutto = request.POST.get('param6')
            par1 = check_salary(request.POST.get('param1'))
            par2 = check_salary(request.POST.get('param2'))
            par3 = check_salary(request.POST.get('param3'))
            par4 = check_salary(request.POST.get('param4'))
            par5 = check_salary(request.POST.get('param5'))
            par6 = check_salary(request.POST.get('param6'))
            graph = Graph(par1, par2, par3, par4, par5, par6, param1_brutto, param2_brutto, param3_brutto, param4_brutto, param5_brutto, param6_brutto)


            graph.draw_graph('wykres.png')

            context = {
                "par1": par1,
                "par2": par2,
                "par3": par3,
                "par4": par4,
                "par5": par5,
                "par6": par6,
                "param1_brutto": param1_brutto,
                "param2_brutto": param2_brutto,
                "param3_brutto": param3_brutto,
                "param4_brutto": param4_brutto,
                "param5_brutto": param5_brutto,
                "param6_brutto": param6_brutto,
            }
            return render(request, 'salary_calc/results.html', context)

    else:
        form = SalaryForm()

    return render(request, 'salary_calc/get_salary.html', { 'form': form})

salary_calc/templates/salary_calc/get_salary.html
{% extends 'base.html' %}

{% block content %}
    <div class="py-5">
        <p>Proszę wypełnić wszystkie pola liczbami z zakresu > 1500</p>
    </div>

<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Przelicz">
</form>
{% endblock  %}

salary_calc/templates/salary_calc/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron">
        <h1 class="display-4">Aplikacja, która wylicza wynagrodzenie brutto na netto.</h1>
        
        <a class="btn btn-primary btn-lg" href="{% url 'salary_calc:get_salary' %}" role="button">Przejdź do formularza!!!</a>
    </div>
{% endblock  %}

salary_calc/templates/salary_calc/results.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <p>Wyniki obliczeń: </p>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Wynagrodzenie brutto</th>
            <th scope="col">Wynagrodzenie netto</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">1</th>
            <td>{{ param1_brutto }}</td>
            <td>{{ par1 }}</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>{{ param2_brutto }}</td>
            <td>{{ par2 }}</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>{{ param3_brutto }}</td>
            <td>{{ par3 }}</td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>{{ param4_brutto }}</td>
            <td>{{ par4 }}</td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>{{ param5_brutto }}</td>
            <td>{{ par5 }}</td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td>{{ param6_brutto }}</td>
            <td>{{ par6 }}</td>
        </tr>
        </tbody>
    </table>

{% endblock  %}

templates/base.html
<!doctype html>
<html lang="pl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Wynagrodzenia</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'salary_calc:index' %}">Wynagrodzenia</a>
    </nav>
    <main class="container py-5">
      {% block content %}
      {% endblock %}
    </main>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>